TITLE = 'Point-Free Foundations'

ITEMS = [
    {
        'id': '1.1',
        'level': 'drill',
        'title': 'Mirror a pair',
        'statement': 'Write mirror(p): the pair with its elements exchanged, point-free. Applying it twice must give the original back.',
        'contract': 'mirror(p) -> pair',
        'tests': '>>> mirror((1, 2))\n(2, 1)\n>>> mirror(mirror((3, 4)))\n(3, 4)',
        'solution': 'mirror = o(tuple, reversed)',
        'note': 'Reads as a sentence: tuple of reversed. No argument ever named.',
    },
    {
        'id': '1.2',
        'level': 'drill',
        'title': 'Record projections',
        'statement': 'A leaderboard record is a (name, score) pair. Write name_of and score_of point-free, without lambdas.',
        'contract': 'name_of(r) -> value; score_of(r) -> value',
        'tests': ">>> name_of(('ada', 95))\n'ada'\n>>> score_of(('ada', 95))\n95",
        'solution': 'name_of, score_of = itemgetter(0), itemgetter(1)',
        'note': "operator.itemgetter is Python's fst/snd -- and it slots straight into map and sorted(key=...).",
    },
    {
        'id': '1.3',
        'level': 'drill',
        'title': 'Default when missing',
        'statement': "Write port_of(cfg): the 'port' entry of a config dict, defaulting to 8080 only when the key is absent. A key holding None is real data and must survive.",
        'contract': 'port_of(cfg) -> value',
        'tests': ">>> port_of({'port': 9000})\n9000\n>>> port_of({})\n8080\n>>> port_of({'port': None}) is None\nTrue",
        'solution': "port_of = lambda cfg: fromMaybe(8080, maybe_get(cfg, 'port'))",
        'note': "The prelude course's or_default cannot pass the third test: with None-as-Nothing, None IS the miss. The NOTHING sentinel is the fix.",
    },
    {
        'id': '1.4',
        'level': 'applied',
        'title': 'Clamp to a range',
        'statement': 'Write clamp(lo, hi): a FUNCTION that forces a number into [lo, hi]. Build it from max and min with partial application -- no lambda in the returned function.',
        'contract': 'clamp(lo, hi) -> (x -> value)',
        'tests': '>>> clamp(0, 10)(15)\n10\n>>> clamp(0, 10)(-5)\n0\n>>> clamp(0, 10)(7)\n7',
        'solution': 'clamp = lambda lo, hi: o(partial(max, lo), partial(min, hi))',
        'note': 'Right to left: cap above with min(hi, .), then floor with max(lo, .). Sections via partial.',
    },
    {
        'id': '1.5',
        'level': 'drill',
        'title': 'Twice',
        'statement': 'Write twice(f): the function that applies f two times.',
        'contract': 'twice(f) -> (x -> value)',
        'tests': ">>> twice(lambda n: n * 3)(2)\n18\n>>> twice(str.strip)('  hi  ')\n'hi'",
        'solution': 'twice = lambda f: o(f, f)',
        'note': 'twice = o on the diagonal. twice(twice(f)) is f four times -- combinators compose with themselves.',
    },
]
