TITLE = 'Point-Free Foundations'

ITEMS = [
    {
        'id': '2.1',
        'level': 'drill',
        'title': 'Mirror a pair',
        'statement': 'Write mirror(p): the pair with its elements exchanged, point-free. Applying it twice must give the original back.',
        'contract': 'mirror(p) -> pair',
        'tests': '>>> mirror((1, 2))\n(2, 1)\n>>> mirror(mirror((3, 4)))\n(3, 4)',
        'solution': 'mirror = o(tuple, reversed)',
        'note': "mirror = o(tuple, reversed) is composition, read right to left: reversed(p) yields the pair's two elements back to front (like an iterator over (p[1], p[0])), and tuple(...) then materializes that into an actual tuple. Because the whole thing is built from function composition, no argument is ever named or indexed -- there is no p[0]/p[1] anywhere in the definition.",
    },
    {
        'id': '2.2',
        'level': 'drill',
        'title': 'Record projections',
        'statement': 'A leaderboard record is a (name, score) pair. Write name_of and score_of point-free, without lambdas.',
        'contract': 'name_of(r) -> value; score_of(r) -> value',
        'tests': ">>> name_of(('ada', 95))\n'ada'\n>>> score_of(('ada', 95))\n95",
        'solution': 'name_of, score_of = itemgetter(0), itemgetter(1)',
        'note': "operator.itemgetter(0) and itemgetter(1) build extractor functions without writing lambda r: r[0] by hand -- itemgetter is exactly Haskell's fst/snd generalized to any index. Because itemgetter returns a genuine function object rather than a lambda, it slots directly into map(name_of, records) or sorted(records, key=score_of) with no wrapping needed.",
    },
    {
        'id': '2.3',
        'level': 'drill',
        'title': 'Default when missing',
        'statement': "Write port_of(cfg): the 'port' entry of a config dict, defaulting to 8080 only when the key is absent. A key holding None is real data and must survive.",
        'contract': 'port_of(cfg) -> value',
        'tests': ">>> port_of({'port': 9000})\n9000\n>>> port_of({})\n8080\n>>> port_of({'port': None}) is None\nTrue",
        'solution': "port_of = lambda cfg: fromMaybe(8080, maybe_get(cfg, 'port'))",
        'note': "maybe_get(cfg, 'port') looks up the key and returns the NOTHING sentinel specifically when the key is absent, never confusing that with a key that is present but stored as None. fromMaybe(8080, ...) only substitutes its default in the NOTHING case, so an explicitly stored None passes through untouched -- which is exactly why the third test (port set to None) must come back as None, not 8080.",
    },
    {
        'id': '2.4',
        'level': 'applied',
        'title': 'Clamp to a range',
        'statement': 'Write clamp(lo, hi): a FUNCTION that forces a number into [lo, hi]. Build it from max and min with partial application -- no lambda in the returned function.',
        'contract': 'clamp(lo, hi) -> (x -> value)',
        'tests': '>>> clamp(0, 10)(15)\n10\n>>> clamp(0, 10)(-5)\n0\n>>> clamp(0, 10)(7)\n7',
        'solution': 'clamp = lambda lo, hi: o(partial(max, lo), partial(min, hi))',
        'note': 'partial(max, lo) and partial(min, hi) each freeze one argument, turning max/min into one-argument functions (Haskell-style sections). Composing them right to left with o means min(hi, x) runs FIRST, capping the value from above, and its result feeds into max(lo, ...), which floors it from below -- both bounds enforced in one pipeline, no if/elif needed.',
    },
    {
        'id': '2.5',
        'level': 'drill',
        'title': 'Twice',
        'statement': 'Write twice(f): the function that applies f two times.',
        'contract': 'twice(f) -> (x -> value)',
        'tests': ">>> twice(lambda n: n * 3)(2)\n18\n>>> twice(str.strip)('  hi  ')\n'hi'",
        'solution': 'twice = lambda f: o(f, f)',
        'note': 'o(f, f) composes f with itself, so twice(f)(x) equals f(f(x)) by definition of composition. Because o is an ordinary function rather than special syntax, nothing stops it from taking the SAME function twice, and applying twice a second time -- twice(twice(f)) -- runs f four times, since composition itself composes.',
    },
]
