TITLE = 'Folds, Scans and Unfolds'

ITEMS = [
    {
        'id': '2.1',
        'level': 'drill',
        'title': 'Parity census',
        'statement': 'Count evens and odds as a pair (evens, odds), in ONE pass, point-free at the top level.',
        'contract': 'parity_counts(xs) -> (evens, odds)',
        'tests': '>>> parity_counts([1, 2, 3, 4])\n(2, 2)\n>>> parity_counts([])\n(0, 0)\n>>> parity_counts([-2, -3])\n(1, 1)',
        'solution': 'parity_counts = partial(foldMap, lambda x: (1 - x % 2, x % 2), both(Sum, Sum))',
        'note': 'both(Sum, Sum) is two counters riding one fold; partial freezes the fold into a name. The [] case is free: monoid identity.',
    },
    {
        'id': '2.2',
        'level': 'drill',
        'title': 'Running balance',
        'statement': 'An account starts at 0; deposits are positive, withdrawals negative. Return every intermediate balance including the start.',
        'contract': 'balances(txs) -> [balance]',
        'tests': '>>> balances([100, -30, -30, 5])\n[0, 100, 70, 40, 45]\n>>> balances([])\n[0]',
        'solution': 'balances = lambda txs: scanl(add, txs, 0)',
        'note': 'Scan = fold that keeps its diary. operator.add instead of a lambda.',
    },
    {
        'id': '2.3',
        'level': 'drill',
        'title': 'Countdown',
        'statement': 'Write countdown(n): the list n, n-1, ..., 1 grown by unfoldr, point-free at the top level.',
        'contract': 'countdown(n) -> [int]',
        'tests': '>>> countdown(4)\n[4, 3, 2, 1]\n>>> countdown(0)\n[]',
        'solution': 'countdown = partial(unfoldr, lambda n: NOTHING if n == 0 else (n, n - 1))',
        'note': 'unfoldr is the anamorphism: seed in, list out, NOTHING stops it.',
    },
    {
        'id': '2.4',
        'level': 'applied',
        'title': 'Digits of a number',
        'statement': 'Write digits(n): the base-10 digits of a non-negative integer, most significant first. Zero has one digit.',
        'contract': 'digits(n) -> [int]',
        'tests': '>>> digits(407)\n[4, 0, 7]\n>>> digits(0)\n[0]',
        'solution': 'digits = lambda n: unfoldr(lambda k: NOTHING if k == 0 else (k % 10, k // 10), n)[::-1] or [0]',
        'note': 'Unfold peels least-significant first; reverse restores reading order. `or [0]` patches the empty unfold at zero.',
    },
    {
        'id': '2.5',
        'level': 'challenge',
        'title': 'Collatz flight length',
        'statement': 'Write collatz_len(n): how many numbers the Collatz sequence visits from n down to 1, inclusive. Even halves; odd triples-plus-one.',
        'contract': 'collatz_len(n) -> int',
        'tests': '>>> collatz_len(6)\n9\n>>> collatz_len(1)\n1',
        'solution': 'collatz_len = lambda n: 1 + len(unfoldr(lambda k: NOTHING if k == 1 else (k, k // 2 if k % 2 == 0 else 3 * k + 1), n))',
        'note': 'The unfold emits everything before the fixed point; +1 counts the 1 itself. No mutation, no while.',
    },
]
