TITLE = 'Folds, Scans and Unfolds'

ITEMS = [
    {
        'id': '3.1',
        'level': 'drill',
        'title': 'Parity census',
        'statement': 'Count evens and odds as a pair (evens, odds), in ONE pass, point-free at the top level.',
        'contract': 'parity_counts(xs) -> (evens, odds)',
        'tests': '>>> parity_counts([1, 2, 3, 4])\n(2, 2)\n>>> parity_counts([])\n(0, 0)\n>>> parity_counts([-2, -3])\n(1, 1)',
        'solution': 'parity_counts = partial(foldMap, lambda x: (1 - x % 2, x % 2), both(Sum, Sum))',
        'note': "foldMap first measures each element with lambda x: (1 - x % 2, x % 2), turning every value into a (is_even, is_odd) pair of 0s and 1s; both(Sum, Sum) then runs two independent Sum folds in lockstep, one over each tuple position. partial freezes the measuring function and the monoid together into a single reusable name, and because Sum's identity is 0, the empty-list case ((0, 0)) falls out for free with no special-casing.",
    },
    {
        'id': '3.2',
        'level': 'drill',
        'title': 'Running balance',
        'statement': 'An account starts at 0; deposits are positive, withdrawals negative. Return every intermediate balance including the start.',
        'contract': 'balances(txs) -> [balance]',
        'tests': '>>> balances([100, -30, -30, 5])\n[0, 100, 70, 40, 45]\n>>> balances([])\n[0]',
        'solution': 'balances = lambda txs: scanl(add, txs, 0)',
        'note': "scanl(add, txs, 0) is a fold that keeps EVERY intermediate accumulator instead of just the final one: starting from the seed 0, it emits the running total after each transaction in txs in turn, so the result is one element longer than the input (it includes the starting balance before any transaction is applied). operator.add stands in for lambda a, b: a + b, following the file's point-free convention.",
    },
    {
        'id': '3.3',
        'level': 'drill',
        'title': 'Countdown',
        'statement': 'Write countdown(n): the list n, n-1, ..., 1 grown by unfoldr, point-free at the top level.',
        'contract': 'countdown(n) -> [int]',
        'tests': '>>> countdown(4)\n[4, 3, 2, 1]\n>>> countdown(0)\n[]',
        'solution': 'countdown = partial(unfoldr, lambda n: NOTHING if n == 0 else (n, n - 1))',
        'note': 'unfoldr grows a list from a seed by repeatedly calling its step function and collecting what it returns. Here the step returns (n, n - 1) -- this element, next seed -- for every n except 0, and returns NOTHING once n hits 0, which unfoldr treats as the stop signal. partial freezes the step function in, so countdown ends up a plain function of n alone.',
    },
    {
        'id': '3.4',
        'level': 'applied',
        'title': 'Digits of a number',
        'statement': 'Write digits(n): the base-10 digits of a non-negative integer, most significant first. Zero has one digit.',
        'contract': 'digits(n) -> [int]',
        'tests': '>>> digits(407)\n[4, 0, 7]\n>>> digits(0)\n[0]',
        'solution': 'digits = lambda n: unfoldr(lambda k: NOTHING if k == 0 else (k % 10, k // 10), n)[::-1] or [0]',
        'note': 'The step function peels off the LEAST-significant digit first (k % 10) and passes what remains onward as the next seed (k // 10), stopping at NOTHING once k reaches 0. Because digits emerge least-significant-first, [::-1] is needed to restore normal reading order; `or [0]` exists because unfoldr(..., 0) immediately returns an empty list (0 stops right away), yet digits(0) must be [0], not [].',
    },
    {
        'id': '3.5',
        'level': 'challenge',
        'title': 'Collatz flight length',
        'statement': 'Write collatz_len(n): how many numbers the Collatz sequence visits from n down to 1, inclusive. Even halves; odd triples-plus-one.',
        'contract': 'collatz_len(n) -> int',
        'tests': '>>> collatz_len(6)\n9\n>>> collatz_len(1)\n1',
        'solution': 'collatz_len = lambda n: 1 + len(unfoldr(lambda k: NOTHING if k == 1 else (k, k // 2 if k % 2 == 0 else 3 * k + 1), n))',
        'note': "The step function encodes the whole rule in one line: halve k when it's even, otherwise 3k + 1, and stop (NOTHING) once k reaches 1. unfoldr therefore emits every number in the sequence EXCEPT the terminal 1, so len(...) counts those steps and +1 accounts for the 1 that was never emitted -- no mutable counter, no while loop, just an unfold, a length, and an addition.",
    },
]
