TITLE = 'The List Gaps'

ITEMS = [
    {
        'id': '4.1',
        'level': 'drill',
        'title': 'Run-length encoding',
        'statement': 'Compress a sequence into (element, count) pairs per maximal run.',
        'contract': 'rle(xs) -> [(x, n)]',
        'tests': ">>> rle('aaabbc')\n[('a', 3), ('b', 2), ('c', 1)]\n>>> rle([])\n[]",
        'solution': 'rle = lambda xs: [(g[0], len(g)) for g in groupBy(eq, xs)]',
        'note': "groupBy(eq, xs) partitions xs into consecutive runs of equal elements (operator.eq supplies the comparison, so no lambda is needed), returning something like [['a','a'],['b']]. The comprehension then turns each run g into (g[0], len(g)) -- the repeated value and how many times it repeated -- which is run-length encoding; groupBy has already done all the actual segmenting.",
    },
    {
        'id': '4.2',
        'level': 'applied',
        'title': 'Moving average',
        'statement': 'Write mavg(n, xs): the n-point moving average of a signal.',
        'contract': 'mavg(n, xs) -> [float]',
        'tests': '>>> mavg(3, [1, 2, 3, 4, 5])\n[2.0, 3.0, 4.0]\n>>> mavg(3, [1, 2])\n[]',
        'solution': 'mavg = lambda n, xs: [sum(w) / n for w in windows(n, xs)]',
        'note': 'windows(n, xs) produces every contiguous length-n slice as its own list -- a genuine sliding window, not index arithmetic -- and the comprehension averages each one with sum(w) / n. Because windows naturally yields zero windows when xs is shorter than n, mavg returns [] for too-short input automatically, with no explicit length check anywhere.',
    },
    {
        'id': '4.3',
        'level': 'drill',
        'title': 'Pagination',
        'statement': 'Write paginate(n, xs): pages of at most n items, last page short.',
        'contract': 'paginate(n, xs) -> [[x]]',
        'tests': '>>> paginate(2, [1, 2, 3, 4, 5])\n[[1, 2], [3, 4], [5]]',
        'solution': 'paginate = chunksOf',
        'note': "This is a pure recognition exercise: chunksOf(n, xs) already means ``split xs into pages of size n'', with the final page possibly shorter -- there is nothing left to implement. paginate is chunksOf under a different name for a different domain.",
    },
    {
        'id': '4.4',
        'level': 'applied',
        'title': 'Column sums, ragged',
        'statement': 'Sensor rows arrive with trailing dropouts. Sum each column over the rows that reached it -- point-free.',
        'contract': 'colsums(rows) -> [sum]',
        'tests': '>>> colsums([[1, 2, 3], [4, 5]])\n[5, 7, 3]\n>>> colsums([])\n[]',
        'solution': 'colsums = o(list, partial(map, sum), transpose)',
        'note': "transpose(rows) turns rows into columns, and because it's ragged-safe, a row shorter than the others simply drops out of the columns past its own length instead of raising an error. Once the input is transposed, map(sum, ...) sums each resulting column, and o composes transpose, the mapping, and list-materialization right to left into one pipeline.",
    },
    {
        'id': '4.5',
        'level': 'drill',
        'title': 'Indentation split',
        'statement': 'Split a line into (leading whitespace, rest) as strings, one pass.',
        'contract': 'indent_split(s) -> (str, str)',
        'tests': ">>> indent_split('   x = 1')\n('   ', 'x = 1')\n>>> indent_split('top')\n('', 'top')",
        'solution': "indent_split = lambda s: tuple(''.join(p) for p in span(str.isspace, s))",
        'note': "span(str.isspace, s) walks s and splits it into (leading run of whitespace characters, everything after) as two lists of individual characters, stopping at the first non-whitespace character it meets. Because span works over s as a sequence of characters rather than as a string, ''.join(...) is needed on each half to turn the character lists back into real strings.",
    },
]
