TITLE = 'The List Gaps'

ITEMS = [
    {
        'id': '3.1',
        'level': 'drill',
        'title': 'Run-length encoding',
        'statement': 'Compress a sequence into (element, count) pairs per maximal run.',
        'contract': 'rle(xs) -> [(x, n)]',
        'tests': ">>> rle('aaabbc')\n[('a', 3), ('b', 2), ('c', 1)]\n>>> rle([])\n[]",
        'solution': 'rle = lambda xs: [(g[0], len(g)) for g in groupBy(eq, xs)]',
        'note': 'groupBy(eq, .) does the segmentation; the comprehension just labels each run. operator.eq, no lambda.',
    },
    {
        'id': '3.2',
        'level': 'applied',
        'title': 'Moving average',
        'statement': 'Write mavg(n, xs): the n-point moving average of a signal.',
        'contract': 'mavg(n, xs) -> [float]',
        'tests': '>>> mavg(3, [1, 2, 3, 4, 5])\n[2.0, 3.0, 4.0]\n>>> mavg(3, [1, 2])\n[]',
        'solution': 'mavg = lambda n, xs: [sum(w) / n for w in windows(n, xs)]',
        'note': 'windows names the sliding view; the arithmetic stays arithmetic. Too-short input yields no windows -- correct for free.',
    },
    {
        'id': '3.3',
        'level': 'drill',
        'title': 'Pagination',
        'statement': 'Write paginate(n, xs): pages of at most n items, last page short.',
        'contract': 'paginate(n, xs) -> [[x]]',
        'tests': '>>> paginate(2, [1, 2, 3, 4, 5])\n[[1, 2], [3, 4], [5]]',
        'solution': 'paginate = chunksOf',
        'note': 'Recognize-it drill: pagination IS chunksOf.',
    },
    {
        'id': '3.4',
        'level': 'applied',
        'title': 'Column sums, ragged',
        'statement': 'Sensor rows arrive with trailing dropouts. Sum each column over the rows that reached it -- point-free.',
        'contract': 'colsums(rows) -> [sum]',
        'tests': '>>> colsums([[1, 2, 3], [4, 5]])\n[5, 7, 3]\n>>> colsums([])\n[]',
        'solution': 'colsums = o(list, partial(map, sum), transpose)',
        'note': 'Ragged-safe transpose turns dropouts into short columns instead of exceptions; then it is just map sum.',
    },
    {
        'id': '3.5',
        'level': 'drill',
        'title': 'Indentation split',
        'statement': 'Split a line into (leading whitespace, rest) as strings, one pass.',
        'contract': 'indent_split(s) -> (str, str)',
        'tests': ">>> indent_split('   x = 1')\n('   ', 'x = 1')\n>>> indent_split('top')\n('', 'top')",
        'solution': "indent_split = lambda s: tuple(''.join(p) for p in span(str.isspace, s))",
        'note': 'span is the two-sided takewhile; the join restores strings from character lists.',
    },
]
