TITLE = 'Maybe, Done Right'

ITEMS = [
    {
        'id': '4.1',
        'level': 'drill',
        'title': 'Safe head',
        'statement': 'Write headM(xs): the first element, or NOTHING for an empty sequence. A leading None is data.',
        'contract': 'headM(xs) -> Maybe value',
        'tests': '>>> headM([7, 8])\n7\n>>> headM([]) is NOTHING\nTrue\n>>> headM([None]) is None\nTrue',
        'solution': 'headM = lambda xs: xs[0] if xs else NOTHING',
        'note': 'The third test is the whole point of the sentinel: None rides through as a value.',
    },
    {
        'id': '4.2',
        'level': 'applied',
        'title': 'Deep dictionary path',
        'statement': 'Write pathM(d, ks): follow a key path through nested dicts; NOTHING if any hop is missing. A stored None must survive the trip.',
        'contract': 'pathM(d, ks) -> Maybe value',
        'tests': ">>> d = {'db': {'host': 'local', 'pool': None}}\n>>> pathM(d, ['db', 'host'])\n'local'\n>>> pathM(d, ['db', 'pool']) is None\nTrue\n>>> pathM(d, ['db', 'user']) is NOTHING\nTrue",
        'solution': 'pathM = lambda d, ks: foldl(lambda m, k: bind(m, lambda t: maybe_get(t, k)), ks, d)',
        'note': "A path lookup is a FOLD of binds over the keys -- the Maybe monad's signature move.",
    },
    {
        'id': '4.3',
        'level': 'drill',
        'title': 'Salvage the parseable',
        'statement': 'Given strings, keep the ones that are integers, as ints, dropping the rest.',
        'contract': 'salvage_ints(ss) -> [int]',
        'tests': ">>> salvage_ints(['3', 'x', '-7', ''])\n[3, -7]",
        'solution': "salvage_ints = lambda ss: catMaybes([int(s) if s.lstrip('-').isdigit() and s else NOTHING for s in ss])",
        'note': 'Map into Maybe, then catMaybes sweeps the failures out -- mapMaybe in two named steps.',
    },
    {
        'id': '4.4',
        'level': 'applied',
        'title': 'All keys or nothing',
        'statement': 'Write need(d, ks): the values for ks in order, or NOTHING if ANY key is absent.',
        'contract': 'need(d, ks) -> Maybe [value]',
        'tests': ">>> need({'a': 1, 'b': 2}, ['a', 'b'])\n[1, 2]\n>>> need({'a': 1}, ['a', 'b']) is NOTHING\nTrue",
        'solution': 'need = lambda d, ks: sequenceM([maybe_get(d, k) for k in ks])',
        'note': 'sequenceM is the all-or-nothing gate: one miss poisons the batch.',
    },
    {
        'id': '4.5',
        'level': 'challenge',
        'title': 'First responder',
        'statement': 'Several config sources; write first_set(dicts, k): the value from the FIRST dict that defines k at all -- even as None -- else NOTHING.',
        'contract': 'first_set(dicts, k) -> Maybe value',
        'tests': ">>> first_set([{}, {'x': None}, {'x': 3}], 'x') is None\nTrue\n>>> first_set([{}, {}], 'x') is NOTHING\nTrue",
        'solution': 'first_set = lambda dicts, k: mconcat(First, [maybe_get(d, k) for d in dicts])',
        'note': "First's identity is NOTHING, so 'defined as None' beats 'undefined' -- exactly the override semantics config layering needs.",
    },
]
