TITLE = 'Maybe, Done Right'

ITEMS = [
    {
        'id': '5.1',
        'level': 'drill',
        'title': 'Safe head',
        'statement': 'Write headM(xs): the first element, or NOTHING for an empty sequence. A leading None is data.',
        'contract': 'headM(xs) -> Maybe value',
        'tests': '>>> headM([7, 8])\n7\n>>> headM([]) is NOTHING\nTrue\n>>> headM([None]) is None\nTrue',
        'solution': 'headM = lambda xs: xs[0] if xs else NOTHING',
        'note': "The whole exercise is what survives the check: `xs[0] if xs else NOTHING` returns the first element whenever the list is non-empty -- even if that element genuinely IS None, a real stored value -- and only returns the NOTHING sentinel when the list is truly empty. Using plain None to mean ``empty'' would make a list starting with None indistinguishable from an empty list, which is exactly the ambiguity the third test is built to catch.",
    },
    {
        'id': '5.2',
        'level': 'applied',
        'title': 'Deep dictionary path',
        'statement': 'Write pathM(d, ks): follow a key path through nested dicts; NOTHING if any hop is missing. A stored None must survive the trip.',
        'contract': 'pathM(d, ks) -> Maybe value',
        'tests': ">>> d = {'db': {'host': 'local', 'pool': None}}\n>>> pathM(d, ['db', 'host'])\n'local'\n>>> pathM(d, ['db', 'pool']) is None\nTrue\n>>> pathM(d, ['db', 'user']) is NOTHING\nTrue",
        'solution': 'pathM = lambda d, ks: foldl(lambda m, k: bind(m, lambda t: maybe_get(t, k)), ks, d)',
        'note': "foldl threads the dictionary through each key in ks one at a time; at every step, bind(m, lambda t: maybe_get(t, k)) either descends into the next nested dict (if the lookup so far succeeded) or short-circuits straight to NOTHING the moment any key along the path is missing. This is the Maybe monad's signature move: a chain of possibly-failing steps where one failure propagates to the very end without an if-chain anywhere.",
    },
    {
        'id': '5.3',
        'level': 'drill',
        'title': 'Salvage the parseable',
        'statement': 'Given strings, keep the ones that are integers, as ints, dropping the rest.',
        'contract': 'salvage_ints(ss) -> [int]',
        'tests': ">>> salvage_ints(['3', 'x', '-7', ''])\n[3, -7]",
        'solution': "salvage_ints = lambda ss: catMaybes([int(s) if s.lstrip('-').isdigit() and s else NOTHING for s in ss])",
        'note': "Each string passes through an inline test-then-convert expression that yields either its integer value or NOTHING (rejecting empty strings and anything that isn't a valid, possibly-negative integer); catMaybes then filters out every NOTHING, keeping only the strings that actually parsed. This is mapMaybe's job split into two explicit, named steps.",
    },
    {
        'id': '5.4',
        'level': 'applied',
        'title': 'All keys or nothing',
        'statement': 'Write need(d, ks): the values for ks in order, or NOTHING if ANY key is absent.',
        'contract': 'need(d, ks) -> Maybe [value]',
        'tests': ">>> need({'a': 1, 'b': 2}, ['a', 'b'])\n[1, 2]\n>>> need({'a': 1}, ['a', 'b']) is NOTHING\nTrue",
        'solution': 'need = lambda d, ks: sequenceM([maybe_get(d, k) for k in ks])',
        'note': "sequenceM is handed a list of Maybe values, one maybe_get per requested key, and returns the fully unwrapped list only if EVERY lookup succeeded; the instant any single lookup comes back NOTHING, the whole result collapses to NOTHING. That is precisely ``all keys present, or nothing at all'' -- no manual all()-style checking required.",
    },
    {
        'id': '5.5',
        'level': 'challenge',
        'title': 'First responder',
        'statement': 'Several config sources; write first_set(dicts, k): the value from the FIRST dict that defines k at all -- even as None -- else NOTHING.',
        'contract': 'first_set(dicts, k) -> Maybe value',
        'tests': ">>> first_set([{}, {'x': None}, {'x': 3}], 'x') is None\nTrue\n>>> first_set([{}, {}], 'x') is NOTHING\nTrue",
        'solution': 'first_set = lambda dicts, k: mconcat(First, [maybe_get(d, k) for d in dicts])',
        'note': "mconcat folds the list of per-dict lookups through the First monoid, whose combining rule is ``keep the first non-NOTHING value seen, ignore the rest''; because First's identity element IS NOTHING, an empty list of dicts (or one where every dict is missing the key) correctly yields NOTHING with no base case to write by hand.",
    },
]
