TITLE = 'Parser Combinators'

ITEMS = [
    {
        'id': '7.1',
        'level': 'drill',
        'title': 'Comma-separated integers',
        'statement': 'Parse a comma-separated integer list, whitespace-blind, whole input consumed.',
        'contract': 'int_list(s) -> Either [int]',
        'tests': '>>> int_list(\'1, -2 , 3\')\n(\'ok\', [1, -2, 3])\n>>> int_list(\'1, x\')\n(\'err\', "unconsumed input: \', x\'")',
        'solution': "int_list = lambda s: runParser(sepBy(rx(r'-?\\d+', int), lit(',')), s)",
        'note': 'sepBy handles the fencepost (separators BETWEEN items); runParser demands the input be spent and lands in Either.',
    },
    {
        'id': '7.2',
        'level': 'drill',
        'title': 'key=value line',
        'statement': "Parse one 'key = value' assignment into a pair; keys are words, values run to end of line.",
        'contract': 'kv(s) -> Either (k, v)',
        'tests': ">>> kv('host = 10.0.0.1')\n('ok', ('host', '10.0.0.1'))\n>>> kv('= oops')[0]\n'err'",
        'solution': "@doP\ndef _kv():\n    k = yield rx(r'\\w+')\n    yield lit('=')\n    v = yield rx(r'[^\\n]+', str.strip)\n    return (k, v)\nkvline = _kv()\nkv = lambda s: runParser(kvline, s)",
        'note': "Three yields, no rest-threading anywhere. kvline is reusable -- chapter 9's INI reader is built on it.",
    },
    {
        'id': '7.3',
        'level': 'drill',
        'title': 'CSV row',
        'statement': 'Split one unquoted CSV row into stripped fields.',
        'contract': 'csv_row(s) -> Either [str]',
        'tests': ">>> csv_row('ada, 95, pass')\n('ok', ['ada', '95', 'pass'])",
        'solution': "csv_row = lambda s: runParser(sepBy(rx(r'[^,\\n]+', str.strip), lit(',')), s)",
        'note': 'The same sepBy skeleton as 7.1 with a different token -- combinator reuse is the whole pitch.',
    },
    {
        'id': '7.4',
        'level': 'applied',
        'title': 'ISO date',
        'statement': 'Parse YYYY-MM-DD into an (y, m, d) integer triple, rejecting month 13.',
        'contract': 'iso_date(s) -> Either (y, m, d)',
        'tests': ">>> iso_date('2026-09-17')\n('ok', (2026, 9, 17))\n>>> iso_date('2026-13-01')\n('err', 'bad month: 13')",
        'solution': "num = lambda n: rx(r'\\d{%d}' % n, int)\n@doP\ndef _date():\n    y = yield num(4)\n    yield lit('-')\n    m = yield num(2)\n    yield lit('-')\n    d = yield num(2)\n    return (y, m, d)\niso_date = lambda s: bindE(runParser(_date(), s),\n    lambda t: Ok(t) if 1 <= t[1] <= 12 else Err(f'bad month: {t[1]}'))",
        'note': 'Parse the shape with doP, judge the meaning with bindE -- syntax and semantics in separate layers.',
    },
    {
        'id': '7.5',
        'level': 'challenge',
        'title': 'Sums and differences',
        'statement': 'Parse and evaluate a left-associative +/- chain over integers.',
        'contract': 'sums(s) -> Either int',
        'tests': ">>> sums('10 - 3 - 2 + 1')\n('ok', 6)\n>>> sums('10 -')[0]\n'err'",
        'solution': "sums = lambda s: runParser(chainl1(rx(r'-?\\d+', int), {'+': add, '-': sub}), s)",
        'note': 'chainl1 IS left-associativity-as-a-fold; operator.add/sub keep it point-free. Chapter 9 grows this into the full calculator.',
    },
]
