TITLE = 'Parser Combinators'

ITEMS = [
    {
        'id': '8.1',
        'level': 'drill',
        'title': 'Comma-separated integers',
        'statement': 'Parse a comma-separated integer list, whitespace-blind, whole input consumed.',
        'contract': 'int_list(s) -> Either [int]',
        'tests': '>>> int_list(\'1, -2 , 3\')\n(\'ok\', [1, -2, 3])\n>>> int_list(\'1, x\')\n(\'err\', "unconsumed input: \', x\'")',
        'solution': "int_list = lambda s: runParser(sepBy(rx(r'-?\\d+', int), lit(',')), s)",
        'note': "sepBy(rx(...), lit(',')) parses one or more integer tokens separated by literal commas, correctly handling the fencepost problem (n items need only n - 1 separators) with no manual counting. runParser then additionally demands the ENTIRE input be consumed (rejecting trailing garbage) and reports the outcome as an Either instead of a bare value-or-FAIL.",
    },
    {
        'id': '8.2',
        'level': 'drill',
        'title': 'key=value line',
        'statement': "Parse one 'key = value' assignment into a pair; keys are words, values run to end of line.",
        'contract': 'kv(s) -> Either (k, v)',
        'tests': ">>> kv('host = 10.0.0.1')\n('ok', ('host', '10.0.0.1'))\n>>> kv('= oops')[0]\n'err'",
        'solution': "@doP\ndef _kv():\n    k = yield rx(r'\\w+')\n    yield lit('=')\n    v = yield rx(r'[^\\n]+', str.strip)\n    return (k, v)\nkvline = _kv()\nkv = lambda s: runParser(kvline, s)",
        'note': "Three sequential yields inside a doP block: match an identifier, match and discard a literal '=', then match everything up to end of line (stripped) as the value. @doP threads the unconsumed remainder of the string from one yield to the next automatically, so no explicit ``rest of string'' variable is passed by hand anywhere. Defining kvline once means the same parser value can be reused later -- chapter 9's INI reader is built directly on it.",
    },
    {
        'id': '8.3',
        'level': 'drill',
        'title': 'CSV row',
        'statement': 'Split one unquoted CSV row into stripped fields.',
        'contract': 'csv_row(s) -> Either [str]',
        'tests': ">>> csv_row('ada, 95, pass')\n('ok', ['ada', '95', 'pass'])",
        'solution': "csv_row = lambda s: runParser(sepBy(rx(r'[^,\\n]+', str.strip), lit(',')), s)",
        'note': "Structurally identical to 8.1's comma-separated integers, just with a token parser that matches and strips arbitrary non-comma text instead of digits. Recognizing that a CSV row and a list of integers are the same shape with a different token is the entire exercise -- sepBy itself doesn't change at all.",
    },
    {
        'id': '8.4',
        'level': 'applied',
        'title': 'ISO date',
        'statement': 'Parse YYYY-MM-DD into an (y, m, d) integer triple, rejecting month 13.',
        'contract': 'iso_date(s) -> Either (y, m, d)',
        'tests': ">>> iso_date('2026-09-17')\n('ok', (2026, 9, 17))\n>>> iso_date('2026-13-01')\n('err', 'bad month: 13')",
        'solution': "num = lambda n: rx(r'\\d{%d}' % n, int)\n@doP\ndef _date():\n    y = yield num(4)\n    yield lit('-')\n    m = yield num(2)\n    yield lit('-')\n    d = yield num(2)\n    return (y, m, d)\niso_date = lambda s: bindE(runParser(_date(), s),\n    lambda t: Ok(t) if 1 <= t[1] <= 12 else Err(f'bad month: {t[1]}'))",
        'note': "_date parses three fixed-width numeric fields (4 digits, 2 digits, 2 digits) separated by literal dashes via doP, producing a raw (year, month, day) tuple purely from the STRING SHAPE, with no awareness of what a valid month even is. bindE then takes that successfully-parsed tuple and applies a semantic check -- is the month between 1 and 12 -- as a separate stage, turning an otherwise-valid parse into an Err if the calendar rule is broken. Keeping ``does this look like a date'' and ``is this a real date'' as two stages means either can change without touching the other.",
    },
    {
        'id': '8.5',
        'level': 'challenge',
        'title': 'Sums and differences',
        'statement': 'Parse and evaluate a left-associative +/- chain over integers.',
        'contract': 'sums(s) -> Either int',
        'tests': ">>> sums('10 - 3 - 2 + 1')\n('ok', 6)\n>>> sums('10 -')[0]\n'err'",
        'solution': "sums = lambda s: runParser(chainl1(rx(r'-?\\d+', int), {'+': add, '-': sub}), s)",
        'note': "chainl1 takes a token parser (digits) and a dict mapping operator characters to their Python functions, and folds a sequence of ``number, operator, number, operator, number...'' strictly left to right, matching how ordinary arithmetic associates addition and subtraction. operator.add/sub are used directly as the combining functions instead of hand-written lambdas, keeping the whole solution point-free.",
    },
]
